name = "OpticalBlochEquations"
uuid = "2604418b-be7b-43f5-81c6-21ef1c423e5b"
authors = ["Dace Osīte", "Florian Gahbauer", "Janis Strods"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
